version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmy-secret-pw"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build: ./backend
    container_name: backend-container
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8084:8084"

  frontend:
      build: ./frontend
      container_name: frontend-container
      env_file:
        - ./frontend/.env
      depends_on:
        - backend
      ports:
        - "5173:8080"


volumes:
  mysql-data: