"""add status to applications

Revision ID: 34152472d095
Revises: 08a351104df7
Create Date: 2026-09-06 21:15:22.245512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34152472d095"
down_revision: Union[str, Sequence[str], None] = "08a351104df7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("resume_path", sa.String(length=1024), nullable=False)
    )
    op.add_column(
        "applications",
        sa.Column("resume_original_filename", sa.String(length=1024), nullable=False),
    )
    op.add_column(
        "applications",
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="applicationstatus"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "status")
    op.drop_column("applications", "resume_original_filename")
    op.drop_column("applications", "resume_path")
    # ### end Alembic commands ###
