"""use text type for descriptions

Revision ID: 4bc87068c691
Revises: b4e0b894764a
Create Date: 2026-09-07 16:04:40.472548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "4bc87068c691"
down_revision: Union[str, Sequence[str], None] = "b4e0b894764a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "offers",
        "geocoding_source",
        existing_type=mysql.VARCHAR(length=1024),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "skills",
        "description",
        existing_type=mysql.VARCHAR(length=256),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "skills",
        "description",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "offers",
        "geocoding_source",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
