"""use text type for descriptions

Revision ID: 6be271997683
Revises: b2abb2e1c9aa
Create Date: 2026-09-07 16:02:08.353048

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6be271997683"
down_revision: Union[str, Sequence[str], None] = "b2abb2e1c9aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiences",
        "description",
        existing_type=mysql.VARCHAR(length=256),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "offers",
        "description",
        existing_type=mysql.VARCHAR(length=2056),
        type_=sa.String(length=16382),
        existing_nullable=False,
    )
    op.alter_column(
        "offers",
        "geocoding_source",
        existing_type=mysql.VARCHAR(length=1024),
        type_=sa.String(length=16382),
        existing_nullable=False,
    )
    op.alter_column(
        "skills",
        "description",
        existing_type=mysql.VARCHAR(length=256),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "skills",
        "description",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "offers",
        "geocoding_source",
        existing_type=sa.String(length=16382),
        type_=mysql.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "offers",
        "description",
        existing_type=sa.String(length=16382),
        type_=mysql.VARCHAR(length=2056),
        existing_nullable=False,
    )
    op.alter_column(
        "experiences",
        "description",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=256),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
