"""Add geocoding fields to offer

Revision ID: 8776c0442212
Revises:
Create Date: 2026-09-04 09:02:09.701562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8776c0442212"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_availabilities")
    op.drop_table("availability_days")
    op.drop_table("availabilities")
    op.drop_table("offer_availabilities")
    op.add_column("offers", sa.Column("adress", sa.String(), nullable=True))
    op.add_column("offers", sa.Column("geocoding_source", sa.String(), nullable=False))
    op.add_column("offers", sa.Column("geocoding_score", sa.Float(), nullable=True))
    op.add_column("offers", sa.Column("latitude", sa.Float(), nullable=False))
    op.add_column("offers", sa.Column("longitude", sa.Float(), nullable=False))
    op.drop_index(op.f("contract_type"), table_name="offers")
    op.drop_column("offers", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offers", sa.Column("status", mysql.ENUM("OPEN", "CLOSED"), nullable=False)
    )
    op.create_index(op.f("contract_type"), "offers", ["contract_type"], unique=True)
    op.drop_column("offers", "longitude")
    op.drop_column("offers", "latitude")
    op.drop_column("offers", "geocoding_score")
    op.drop_column("offers", "geocoding_source")
    op.drop_column("offers", "adress")
    op.create_table(
        "offer_availabilities",
        sa.Column(
            "availability_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("offer_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["availabilities.id"],
            name=op.f("offer_availabilities_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offers.id"],
            name=op.f("offer_availabilities_ibfk_2"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("availability_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "availabilities",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "availability_days",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "day",
            mysql.ENUM(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
            ),
            nullable=False,
        ),
        sa.Column("start_time", mysql.TIME(), nullable=False),
        sa.Column("end_time", mysql.TIME(), nullable=False),
        sa.Column(
            "availability_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["availabilities.id"],
            name=op.f("availability_days_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_availabilities",
        sa.Column(
            "availability_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("start_date", sa.DATE(), nullable=False),
        sa.Column("end_date", sa.DATE(), nullable=False),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["availabilities.id"],
            name=op.f("user_availabilities_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_availabilities_ibfk_2"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("availability_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
