"""change size of description

Revision ID: b2abb2e1c9aa
Revises: c00d5996cbbb
Create Date: 2026-09-07 15:43:41.884182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b2abb2e1c9aa"
down_revision: Union[str, Sequence[str], None] = "c00d5996cbbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("cover_letter_path", sa.String(length=1024), nullable=False),
    )
    op.add_column(
        "applications",
        sa.Column(
            "cover_letter_original_filename", sa.String(length=1024), nullable=False
        ),
    )
    op.alter_column(
        "experiences",
        "description",
        existing_type=mysql.VARCHAR(length=256),
        type_=sa.String(length=32000),
        existing_nullable=True,
    )
    op.alter_column(
        "offers",
        "description",
        existing_type=mysql.VARCHAR(length=2056),
        type_=sa.String(length=32000),
        existing_nullable=False,
    )
    op.alter_column(
        "skills",
        "description",
        existing_type=mysql.VARCHAR(length=256),
        type_=sa.String(length=32000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "skills",
        "description",
        existing_type=sa.String(length=32000),
        type_=mysql.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "offers",
        "description",
        existing_type=sa.String(length=32000),
        type_=mysql.VARCHAR(length=2056),
        existing_nullable=False,
    )
    op.alter_column(
        "experiences",
        "description",
        existing_type=sa.String(length=32000),
        type_=mysql.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.drop_column("applications", "cover_letter_original_filename")
    op.drop_column("applications", "cover_letter_path")
    # ### end Alembic commands ###
