"""change update_at by created_at in application db

Revision ID: c00d5996cbbb
Revises: e5a8a7e355ba
Create Date: 2026-09-07 12:35:40.781768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c00d5996cbbb"
down_revision: Union[str, Sequence[str], None] = "e5a8a7e355ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.drop_column("applications", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("updated_at", mysql.DATETIME(), nullable=False)
    )
    op.drop_column("applications", "created_at")
    # ### end Alembic commands ###
