"""initial schema

Revision ID: dde4cddf6e88
Revises: 5554dccaa79b
Create Date: 2026-09-04 12:13:35.216072

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "dde4cddf6e88"
down_revision: Union[str, Sequence[str], None] = "5554dccaa79b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
