name: push_to_mirror

on:
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
  push:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  push_to_mirror:
    if: ${{ github.repository_owner == vars.USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - run: git fetch --unshallow
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.FULL_MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}