import os

ALGORITHM = "HS256"
AUTH_TOKEN_EXPIRE_MINUTES = 20
SECRET_KEY = os.getenv("SECRET_KEY")
BASE_OFFER_DETECTION_RADIUS_M = int(os.getenv("BASE_OFFER_DETECTION_RADIUS_M", 300))
GOUV_ADDRESS_API_URL=os.getenv("GOUV_ADDRESS_API_URL")
